### ISSUE TITLE
2022.5.6，这东西好像用不了

### ISSUE THREAD

**Issue by mocusez** [qinlili23333/CC-ATTIS#1]
h5p的题目做不了，而下面的代码让人困惑，好像每点一次“下一章”计数加一？
![AC5%AH ES)B %IEH{Y@7M$U](https://user-images.githubusercontent.com/57286919/167086751-86c43376-c501-4cb3-b4ef-6aae31129b47.png)

**Comment by mocusez** [comment]
测试的是XUT的，也许是真的不支持

**Comment by qinlili23333** [comment]
题目只要打开，不需要做就会在记录里显示打勾，应付大部分老师仅检查完成率用

**Comment by mocusez** [comment]
啊这，我们这边老师是看grade的，测试完后完成度仅20%:cold_sweat:
不过还是要谢谢这个项目，我去研究下h5p问题怎么处理，issue我就关了

**Comment by qinlili23333** [comment]
> 啊这，我们这边老师是看grade的，测试完后完成度仅20%😰 不过还是要谢谢这个项目，我去研究下h5p问题怎么处理，issue我就关了


欢迎提交更多功能的pr，只要是有意义的功能我都会合并
